services:
  # node:
  #   build:
  #     context: .
  #     dockerfile: node.Dockerfile
  #   restart: always
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=timekeeping
    ports:
      - 3306:3306
